[project]
name = "whatsapp-status-checker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "art==5.9",
    "ipykernel>=6.30.1",
    "pyautogui>=0.9.54",
    "python-dotenv>=1.1.1",
    "python-whatsapp-bot>=2.0.3",
    "pytz==2021.3",
    "selenium==4.8.2",
    "whatsappcloud==0.0.5",
    "beautifulsoup4==4.13.5"
]

[tool.setuptools.packages.find]
where = ["src"]